name: SecurityCodeScan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Add security analyzer
        run: dotnet add AtlasForense.csproj package SecurityCodeScan.VS2019 --version 5.6.7
      - name: Build with security analyzer
        run: dotnet build AtlasForense.slnx --configuration Release --no-restore
